version: '3.7'

services:
  customer_service:
    build: ./customer-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - ./customer-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://customer_db_username:customer_db_password@customer_db/customer_db_dev
    depends_on:
       - customer_db
  
  customer_db:
    image: postgres:latest
    volumes:
      - postgres_data_customer:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=customer_db_username
      - POSTGRES_PASSWORD=customer_db_password
      - POSTGRES_DB=customer_db_dev
    logging:
        driver: none 

  product_service:
    build: ./product-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - ./product-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://product_db_username:product_db_password@product_db/product_db_dev
    logging:
        driver: none 

  product_db:
    image: postgres:latest
    volumes:
      - postgres_data_product:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=product_db_username
      - POSTGRES_PASSWORD=product_db_password
      - POSTGRES_DB=product_db_dev
    logging:
        driver: none 

  price_service:
    build: ./price-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - ./price-service/:/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URI=postgresql://price_db_username:price_db_password@price_db/price_db_dev

  order_service:
    build: ./order-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - ./order-service/:/app/
    ports:
      - 8004:8000
    environment:
      - DATABASE_URI=postgresql://order_db_username:order_db_password@order_db/order_db_dev

  order_db:
    image: postgres:latest
    volumes:
      - postgres_data_order:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=order_db_username
      - POSTGRES_PASSWORD=order_db_password
      - POSTGRES_DB=order_db_dev
    logging:
        driver: none 

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - customer_service
      - product_service
      - price_service
      - order_service

volumes:
  postgres_data_customer:
  postgres_data_product:
  postgres_data_price:
  postgres_data_order:
